In [2]:
#import libraries
import numpy as np
import pandas as pd
from pandas import *
import sys

## Concatenate

### Numpy concatenation

In [3]:

arr1=np.arange(1,10).reshape((3,3))

In [4]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr2=np.arange(10,19).reshape((3,3))
arr2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [6]:
#Concatenate along columns
new_arr=np.concatenate([arr1,arr2],axis=1)
new_arr

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [7]:
#Concatenate along rows
new_arr=np.concatenate([arr1,arr2],axis=0)
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

### Series Concatenation

In [8]:
ser1=pd.Series([10,15,20,25],index=['a','b','c','d'])
ser2=pd.Series([99,88,77],index=['x','y','z'])


In [9]:
print(ser1)
print(ser2)

a    10
b    15
c    20
d    25
dtype: int64
x    99
y    88
z    77
dtype: int64


In [10]:
#concatenate using pandas (along rows)
new_ser=pd.concat([ser1,ser2])
new_ser

a    10
b    15
c    20
d    25
x    99
y    88
z    77
dtype: int64

In [11]:
#concatenate using pandas ( trying against columns)
new_ser=pd.concat([ser1,ser2],axis=1)
new_ser

0     1
a  10.0   NaN
b  15.0   NaN
c  20.0   NaN
d  25.0   NaN
x   NaN  99.0
y   NaN  88.0
z   NaN  77.0

#### Result is a new dataframe with 2 columns and null values 

In [12]:
#concatenate using pandas ( trying against columns)
new_ser=pd.concat([ser1,ser2],keys=['category1','category2'])
new_ser

category1  a    10
           b    15
           c    20
           d    25
category2  x    99
           y    88
           z    77
dtype: int64

In [13]:
print(new_ser.keys())

MultiIndex(levels=[[u'category1', u'category2'], [u'a', u'b', u'c', u'd', u'x', u'y', u'z']],
           labels=[[0, 0, 0, 0, 1, 1, 1], [0, 1, 2, 3, 4, 5, 6]])


In [14]:
new_ser.values

array([10, 15, 20, 25, 99, 88, 77])

### Dataframe Concatenation

In [15]:
#create 2 dataframes
df1=pd.DataFrame(np.random.randn(4,3),columns=['a','b','c'])
df2=pd.DataFrame(np.random.randn(3,3),columns=['x','b','z'])


In [16]:
df1

a         b         c
0 -0.480782  1.318553 -0.084593
1 -0.176781  0.630335  0.579953
2 -0.045043 -1.564590 -0.161915
3  0.605766 -0.167029  1.023604

In [17]:
df2

x         b         z
0  0.286968 -1.731971  1.335622
1 -0.403439  0.941183 -1.145113
2  0.833594 -0.270892 -1.443735

In [57]:
#concatenate  
df_new=pd.concat([df1,df2])

In [58]:
df_new

a         b         c         x         z
0 -0.480782  1.318553 -0.084593       NaN       NaN
1 -0.176781  0.630335  0.579953       NaN       NaN
2 -0.045043 -1.564590 -0.161915       NaN       NaN
3  0.605766 -0.167029  1.023604       NaN       NaN
0       NaN -1.731971       NaN  0.286968  1.335622
1       NaN  0.941183       NaN -0.403439 -1.145113
2       NaN -0.270892       NaN  0.833594 -1.443735

In [20]:
df_new=pd.concat([df1,df2],ignore_index=True)

In [21]:
df_new

a         b         c         x         z
0 -0.480782  1.318553 -0.084593       NaN       NaN
1 -0.176781  0.630335  0.579953       NaN       NaN
2 -0.045043 -1.564590 -0.161915       NaN       NaN
3  0.605766 -0.167029  1.023604       NaN       NaN
4       NaN -1.731971       NaN  0.286968  1.335622
5       NaN  0.941183       NaN -0.403439 -1.145113
6       NaN -0.270892       NaN  0.833594 -1.443735

## Pivoting

In [22]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'TestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3]}
df = pd.DataFrame(raw_data, columns = ['regiment', 'company', 'TestScore'])
df

regiment company  TestScore
0   Nighthawks     1st          4
1   Nighthawks     1st         24
2   Nighthawks     2nd         31
3   Nighthawks     2nd          2
4     Dragoons     1st          3
5     Dragoons     1st          4
6     Dragoons     2nd         24
7     Dragoons     2nd         31
8       Scouts     1st          2
9       Scouts     1st          3
10      Scouts     2nd          2
11      Scouts     2nd          3

In [23]:
pd.pivot_table(df, index=['regiment'], aggfunc='sum')

TestScore
regiment             
Dragoons           62
Nighthawks         61
Scouts             10

In [24]:
pd.pivot_table(df, index=['company'], aggfunc='mean')

TestScore
company           
1st       6.666667
2nd      15.500000

## Duplicate Data

In [25]:
#create dataframe using list & dictionary
lst_1=['a','b','c','b','c']
lst_2=[1,2,3,2,3]
dictionary=dict(zip(lst_1,lst_2))

In [26]:
dictionary

{'a': 1, 'b': 2, 'c': 3}

In [27]:
df=pd.DataFrame({'name':['pramod','akshay','deepak','ziaan','pramod','akshay','pramod'],
            'age':[31,25,30,2,31,25,12]})

In [28]:
df

age    name
0   31  pramod
1   25  akshay
2   30  deepak
3    2   ziaan
4   31  pramod
5   25  akshay
6   12  pramod

In [29]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
6    False
dtype: bool

In [30]:
df.drop_duplicates()

age    name
0   31  pramod
1   25  akshay
2   30  deepak
3    2   ziaan
6   12  pramod

In [31]:
df.drop_duplicates('name')

age    name
0   31  pramod
1   25  akshay
2   30  deepak
3    2   ziaan

In [32]:
df.drop_duplicates('age')

age    name
0   31  pramod
1   25  akshay
2   30  deepak
3    2   ziaan
6   12  pramod

## Mapping

In [33]:
df=pd.DataFrame({'profession':['sports','IT','Medical','Finance','Edu','Legal','Politics'],
                'Avg_age':[20,22,30,45,44,50,60]})

In [34]:
df

Avg_age profession
0       20     sports
1       22         IT
2       30    Medical
3       45    Finance
4       44        Edu
5       50      Legal
6       60   Politics

In [35]:
min_edu_map={'sports':'min','IT':'Btech','Medical':'MBBS','Finance':'MBA','Edu':'Med','Legal':'LLB','Politics':'5th'}

In [36]:
min_edu_map

{'Edu': 'Med',
 'Finance': 'MBA',
 'IT': 'Btech',
 'Legal': 'LLB',
 'Medical': 'MBBS',
 'Politics': '5th',
 'sports': 'min'}

In [37]:
df['min_education']=df['profession'].map(min_edu_map)

In [38]:
df

Avg_age profession min_education
0       20     sports           min
1       22         IT         Btech
2       30    Medical          MBBS
3       45    Finance           MBA
4       44        Edu           Med
5       50      Legal           LLB
6       60   Politics           5th

## Replace

In [39]:
df.replace('Politics','Difference_makers',)

Avg_age         profession min_education
0       20             sports           min
1       22                 IT         Btech
2       30            Medical          MBBS
3       45            Finance           MBA
4       44                Edu           Med
5       50              Legal           LLB
6       60  Difference_makers           5th

## Binning

In [40]:
age=[12,32,43,54,56,5,76,22,18,65,35,48,13,19,26,67,99]

In [41]:
bins=[10,20,30,40,50,60,80,90,100]

In [42]:
pd.cut(age,bins)

[(10, 20], (30, 40], (40, 50], (50, 60], (50, 60], ..., (10, 20], (10, 20], (20, 30], (60, 80], (90, 100]]
Length: 17
Categories (8, interval[int64]): [(10, 20] < (20, 30] < (30, 40] < (40, 50] < (50, 60] < (60, 80] < (80, 90] < (90, 100]]

In [43]:
#check frequcny count
pd.value_counts(pd.cut(age,bins))

(10, 20]     4
(60, 80]     3
(50, 60]     2
(40, 50]     2
(30, 40]     2
(20, 30]     2
(90, 100]    1
(80, 90]     0
dtype: int64

In [44]:
pd.cut(age,3,precision=1)

[(4.9, 36.3], (4.9, 36.3], (36.3, 67.7], (36.3, 67.7], (36.3, 67.7], ..., (4.9, 36.3], (4.9, 36.3], (4.9, 36.3], (36.3, 67.7], (67.7, 99.0]]
Length: 17
Categories (3, interval[float64]): [(4.9, 36.3] < (36.3, 67.7] < (67.7, 99.0]]

In [45]:
pd.value_counts(pd.cut(age,2))

(4.906, 52.0]    11
(52.0, 99.0]      6
dtype: int64

## GroupBy 

In [46]:
!pip install sklearn

In [47]:
from sklearn.datasets import load_boston

In [48]:
boston=load_boston()

In [49]:
boston.data.shape

(506, 13)

In [50]:
df=pd.DataFrame(boston.data,columns=boston.feature_names)

In [51]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [52]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.593761   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.596783   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.647423   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [53]:
from sklearn.datasets import load_iris

In [54]:
iris=load_iris()

In [55]:
iris_df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [56]:
iris_df.shape

(150, 4)